language: java
jdk:
  - openjdk8

# Workaround for buffer overflow with openjdk6
# https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hosts:
    - myshorthost
  hostname: myshorthost

after_success:
  - bash <(curl -s https://codecov.io/bash)
